##################################################################################################
# application configuration
##################################################################################################
info:
  app:
    artifact: '@project.artifactId@'
    version: '@project.version@'
    name: '@project.name@'
    description: '@project.description@'


spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2

    # enable H2 web console and set url for web console
    # http://localhost:8080/console
    h2:
      console:
        enabled: true
        path: /console